Repository prgrms-web-devcourse-final-project/WEB1_2_BUMBLEBEE_FE, pull requests merged in 2024-12, with the labels that each got.

#78 ✨ Feat : 예약 및 결제 api 수정
  src/apis/reservation.ts
  src/pages/PaymentPage/PaymentFailPage.tsx
  src/pages/PaymentPage/PaymentLoadingPage.tsx
  src/pages/PaymentPage/components/PaymentButton.tsx
  src/typings/types.ts
Labels: ✨ Feat

#79 ✨ Feat : 메인 페이지 api 및 지도 수정
  package-lock.json
  package.json
  src/apis/workplace.ts
  src/pages/MainPage/components/KakaoMap.tsx
  src/pages/MainPage/components/MainList.tsx
  src/pages/MainPage/components/StudyRoomCard.tsx
  src/pages/MainPage/hooks/useGetWorkplaceData.tsx
  src/pages/MainPage/index.tsx
  src/typings/types.ts
Labels: ✨ Feat

#80 ✨ Feat : 사업장 상세페이지 상세정보, 룸 선택 탭 api 연결
  src/apis/business.ts
  src/apis/member.ts
  src/apis/review.ts
  src/pages/DetailPage/components/DetailComponent.tsx
  src/pages/DetailPage/components/RoomSelect.tsx
  src/pages/DetailPage/components/TabComponent.tsx
  src/pages/DetailPage/hooks/useGetStudyroomOfWorkplace.ts
  src/pages/DetailPage/hooks/useGetWorkplaceData.ts
  src/pages/DetailPage/index.tsx
  src/pages/HostMypage/components/HostInfo.tsx
  src/pages/RegisterSpace/components/RoomComponent.tsx
  src/pages/UserMypage/components/UserButtonContainer.tsx
  src/pages/UserMypage/components/UserInfo.tsx
  src/pages/UserMypage/hooks/useGetUserData.ts
  src/routes/Router.tsx
Labels: ✨ Feat, 💄 Design

#81 ✨ Feat : 공간 등록 페이지(룸 추가) 구현 완료
  src/apis/index.ts
  src/apis/workplace.ts
  src/pages/RegisterSpace/components/SpaceForm.tsx
  src/pages/RegisterSpace/hooks/usePostWorkPlace.ts
  src/typings/types.ts
Labels: ✨ Feat

#82 ✨ Feat : 메인 페이지 지도 기능 구현 완료
  src/apis/workplace.ts
  src/pages/MainPage/components/KakaoMap.tsx
  src/pages/MainPage/components/MainList.tsx
  src/pages/MainPage/components/StudyRoomCard.tsx
  src/typings/types.ts
Labels: ✨ Feat

#84 ✨ Feat : 사업장 관리 페이지 기능 구현
  src/components/ListStyle.tsx
  src/pages/DetailPage/hooks/useGetStudyroomOfWorkplace.ts
  src/pages/ManagementPlacePage/components/ManagementPlaceCard.tsx
  src/pages/ManagementPlacePage/components/ManagementPlaceList.tsx
  src/pages/ManagementPlacePage/hooks/useDeleteBusinessPlace.ts
  src/pages/ManagementPlacePage/hooks/useGetBusinessWorkplaces.ts
Labels: ✨ Feat

#85 ✨ Feat : 수정 페이지 1차 및 토큰/role 저장
  src/apis/auth.ts
  src/apis/index.ts
  src/pages/AddRoom/components/RoomForm.tsx
  src/pages/ModifySpace/hooks/useGetRoomListInfo.ts
  src/pages/ModifySpace/hooks/useGetWorkPlaceInfo.ts
  src/pages/ModifySpace/index.tsx
  src/pages/RegisterSpace/components/SpaceForm.tsx
  src/routes/Router.tsx
  src/typings/types.ts
  src/utils/auth.ts
Labels: ✨ Feat

#88 ✨ Feat : 결제 페이지 기능 구현 완료
  src/apis/reservation.ts
  src/main.tsx
  src/pages/PaymentPage/PaymentFailPage.tsx
  src/pages/PaymentPage/PaymentLoadingPage.tsx
  src/pages/PaymentPage/components/PaymentButton.tsx
  src/pages/PaymentPage/index.tsx
  src/typings/types.ts
Labels: ✨ Feat

#89 ✨ Feat : 예약 내역 페이지 기능 구현 및 리뷰 작성 페이지 연결 시작
  src/apis/reservation.ts
  src/components/ListStyle.tsx
  src/pages/ReservationListPage/components/ReservationDetailCard.tsx
  src/pages/ReservationListPage/components/ReservationList.tsx
  src/pages/ReservationListPage/hooks/useGetAllMyReservations.ts
  src/pages/ReviewListPage/components/MyReviewCard.tsx
  src/pages/ReviewListPage/components/MyReviewList.tsx
  src/pages/ReviewListPage/hooks/useGetMyReviewList.ts
  src/pages/UserMypage/components/LatestReservation.tsx
  src/pages/UserMypage/components/UserButtonContainer.tsx
  src/pages/UserMypage/hooks/useGetLatestReservation.ts
  src/pages/UserMypage/hooks/useGetMyReservations.ts
  src/pages/WriteReviewPage/components/ReservationInfo.tsx
  src/pages/WriteReviewPage/components/WriteReview.tsx
  src/pages/WriteReviewPage/hooks/usePostReview.ts
  src/pages/WriteReviewPage/index.tsx
  src/typings/types.ts
Labels: ✨ Feat, 💄 Design, 🏷️ Type

#90 ✨ Feat : 리뷰 작성 기능 구현
  src/apis/review.ts
  src/pages/ReservationListPage/components/ReservationDetailCard.tsx
  src/pages/WriteReviewPage/components/ReservationInfo.tsx
  src/pages/WriteReviewPage/components/WriteReview.tsx
  src/pages/WriteReviewPage/hooks/usePostReview.ts
  src/pages/WriteReviewPage/index.tsx
  src/typings/types.ts
Labels: ✨ Feat

#91 ♻️ Refactor, ✨ Feat : 메인 페이지 개선 및 에러 처리
  package-lock.json
  package.json
  src/apis/index.ts
  src/components/Toastify.tsx
  src/main.tsx
  src/pages/MainPage/components/KakaoMap.tsx
  src/pages/MainPage/components/PlaceModal.tsx
  src/pages/MainPage/hooks/useGetWorkplaceData.tsx
  src/pages/PaymentPage/components/PaymentButton.tsx
  src/pages/PaymentPage/index.tsx
  src/pages/SearchPage/components/PlaceList.tsx
  src/pages/SearchPage/components/PlaceSearch.tsx
Labels: ✨ Feat, ♻️ Refactor

#92 ✨ Feat : 회원 정보 조회 페이지 구현 및 정보 수정 기능 완료
  src/apis/member.ts
  src/pages/HostMypage/components/HostInfo.tsx
  src/pages/UserInfoEditPage/components/UserEditContainer.tsx
  src/pages/UserInfoEditPage/components/UserEditForm.tsx
  src/pages/UserInfoEditPage/hooks/usePutEditUserData.ts
  src/pages/UserInfoPage/components/UserInfoBox.tsx
  src/pages/UserInfoPage/components/UserInfoContainer.tsx
  src/pages/UserMypage/components/UserInfo.tsx
  src/pages/UserMypage/hooks/useGetUserData.ts
  src/pages/WriteReviewPage/components/WriteReview.tsx
  src/pages/WriteReviewPage/hooks/usePostReview.ts
  src/typings/types.ts
Labels: ✨ Feat

#93 ✨ Feat : 사업자 정보 수정, 조회 페이지 및 회원 탈퇴 버튼 api 연결
  src/apis/business.ts
  src/components/DeleteAccountButton.tsx
  src/pages/BusinessSignUp/components/BusinessSignUpForm.tsx
  src/pages/HostInfoEditPage/components/HostEditContainer.tsx
  src/pages/HostInfoEditPage/components/HostEditForm.tsx
  src/pages/HostInfoEditPage/hooks/useDeleteBusiness.ts
  src/pages/HostInfoEditPage/hooks/usePutEditBusinessData.ts
  src/pages/HostInfoPage/components/HostInfoBox.tsx
  src/pages/HostInfoPage/components/HostInfoContainer.tsx
  src/pages/HostMypage/components/HostInfo.tsx
  src/pages/HostMypage/hooks/useGetBusinessData.ts
  src/pages/UserInfoEditPage/components/UserEditContainer.tsx
  src/pages/UserInfoEditPage/components/UserEditForm.tsx
  src/pages/UserInfoEditPage/hooks/useDeleteMember.ts
  src/pages/UserInfoPage/components/UserInfoContainer.tsx
  src/pages/UserMypage/components/UserButtonContainer.tsx
  src/pages/UserMypage/hooks/useGetLatestReservation.ts
  src/pages/UserMypage/hooks/useGetUserData.ts
  src/pages/UserSignUp/components/UserSignUpForm.tsx
  src/routes/Router.tsx
Labels: ✨ Feat

#95 ✨ Feat : 결제 취소 버튼 api 연결
  src/apis/reservation.ts
  src/components/Modal.tsx
  src/pages/ReservationListPage/components/ReservationDetailCard.tsx
  src/pages/ReservationListPage/hooks/useCancelPayment.ts
  src/pages/UserMypage/components/LatestReservation.tsx
  src/pages/WriteReviewPage/components/ReservationInfo.tsx
  src/pages/WriteReviewPage/index.tsx
  src/typings/types.ts
Labels: ✨ Feat, 💄 Design

#96 ✨ Feat : 스터디룸 상세 정보 페이지 기능 구현 완료
  src/apis/workplace.ts
  src/pages/PaymentPage/PaymentSuccessPage.tsx
  src/pages/PaymentPage/components/CancelRule.tsx
  src/pages/PaymentPage/index.tsx
  src/pages/ReservationPage/components/ImageCarousel.tsx
  src/pages/ReservationPage/components/ReservationBar.tsx
  src/pages/ReservationPage/components/ReservationDate/ReservationDate.css
  src/pages/ReservationPage/components/ReservationDate/ReservationDate.tsx
  src/pages/ReservationPage/components/ReservationPeople.tsx
  src/pages/ReservationPage/components/ReservationTime.tsx
  src/pages/ReservationPage/components/RoomDetail.tsx
  src/pages/ReservationPage/hooks/useGetPossibleTime.ts
  src/pages/ReservationPage/hooks/useGetStudyroomDetail.ts
  src/pages/ReservationPage/index.tsx
  src/pages/SearchPage/components/SelectTime.tsx
  src/routes/Router.tsx
  src/typings/types.ts
Labels: ✨ Feat, 💄 Design, 🔧 Fix

#98 ✨ Feat : 리뷰 작성 및 조회, 하단 네비게이션 바 기능 구현 완료
  src/apis/reservation.ts
  src/apis/review.ts
  src/layouts/BottomNavigation.tsx
  src/pages/ManagementReserverPage/hooks/useGetReserver.ts
  src/pages/ReservationListPage/components/ReservationDetailCard.tsx
  src/pages/ReviewListPage/components/MyReviewCard.tsx
  src/pages/ReviewListPage/components/MyReviewList.tsx
  src/pages/ReviewListPage/hooks/useGetMyReviewList.ts
  src/pages/UserMypage/components/LatestReservation.tsx
  src/pages/WriteReviewPage/components/WriteReview.tsx
  src/pages/WriteReviewPage/hooks/usePostReview.ts
  src/pages/WriteReviewPage/index.tsx
  src/typings/types.ts
Labels: ✨ Feat

#99 ✨ Feat : 사업자 예약자 조회, 리뷰 작성 완료된 예약 문구 표시 및 리뷰 페이지로 이동
  src/pages/ManagementPlacePage/components/ManagementPlaceCard.tsx
  src/pages/ManagementReserverPage/components/ReserverCard.tsx
  src/pages/ManagementReserverPage/components/ReserverList.tsx
  src/pages/ManagementReserverPage/hooks/useGetReserver.ts
  src/pages/ReservationListPage/components/ReservationDetailCard.tsx
  src/pages/ReviewListPage/components/MyReviewCard.tsx
  src/pages/WriteReviewPage/hooks/usePostReview.ts
  src/typings/types.ts
Labels: ✨ Feat

#100 ✨ Feat : 로그인 페이지 및 상세 페이지 구현 완료
  package-lock.json
  package.json
  src/apis/auth.ts
  src/apis/index.ts
  src/apis/review.ts
  src/pages/DetailPage/components/DetailComponent.tsx
  src/pages/DetailPage/components/ReviewComponent.tsx
  src/pages/DetailPage/components/RoomSelect.tsx
  src/pages/DetailPage/components/TabComponent.tsx
  src/pages/DetailPage/components/WorkPlaceReview.tsx
  src/pages/DetailPage/hooks/useGetWorkplaceData.ts
  src/pages/DetailPage/hooks/useReviewScroll.ts
  src/pages/DetailPage/index.tsx
  src/pages/ModifySpace/components/SpaceModify.tsx
  src/pages/RegisterSpace/components/RoomComponent.tsx
  src/pages/RegisterSpace/components/SpaceForm.tsx
  src/pages/UserLogin/components/OAuth.tsx
  src/typings/types.ts
  src/utils/auth.ts
Labels: ✨ Feat

#102 ✨ Feat, ♻️ Refactor : 검색 페이지 기능 구현 및 예약 결제 페이지 개선
  src/apis/workplace.ts
  src/constants/constants.ts
  src/pages/PaymentPage/components/PaymentButton.tsx
  src/pages/ReservationPage/components/ReservationTime.tsx
  src/pages/ReservationPage/index.tsx
  src/pages/SearchPage/components/PlaceList.tsx
  src/pages/SearchPage/components/PlaceSearch.tsx
  src/pages/SearchPage/components/SelectDate/SelectDate.css
  src/pages/SearchPage/components/SelectDate/SelectDate.tsx
  src/pages/SearchPage/index.tsx
  src/pages/SearchResult/components/ResultBar.tsx
  src/pages/SearchResult/components/RoomCard.tsx
  src/pages/SearchResult/hooks/useGetSearchStudyRoom.ts
  src/pages/SearchResult/index.tsx
  src/store/searchStore.ts
  src/typings/types.ts
Labels: ✨ Feat, ♻️ Refactor

#103 ✨ Feat : 예약 내역 페이지 결제 취소 기능 구현
  src/apis/reservation.ts
  src/pages/ReservationListPage/components/ReservationDetailCard.tsx
  src/pages/ReservationListPage/components/ReservationList.tsx
  src/pages/ReservationListPage/hooks/useCancelPayment.ts
  src/typings/types.ts
Labels: ✨ Feat

#106 ✨ Feat : 채팅 페이지 기능 구현
  index.html
  package-lock.json
  package.json
  src/apis/chat.ts
  src/apis/index.ts
  src/constants/constants.ts
  src/pages/ChatListPage/components/ChatCard.tsx
  src/pages/ChatListPage/hooks/useGetChatList.ts
  src/pages/ChatListPage/index.tsx
  src/pages/ChatPage/components/MessageContainer.tsx
  src/pages/ChatPage/components/MessageInput.tsx
  src/pages/ChatPage/components/ReceiveMessage.tsx
  src/pages/ChatPage/components/SendMessage.tsx
  src/pages/ChatPage/index.tsx
  src/pages/DetailPage/components/DetailNavigation.tsx
  src/pages/DetailPage/index.tsx
  src/pages/SearchResult/components/RoomCard.tsx
  src/routes/Router.tsx
  src/typings/types.ts
  src/utils/formatTime.ts
  vite.config.ts
Labels: ✨ Feat

#107 ✨ Feat : 사업장 삭제 시 s3 사업장 사진 폴더도 삭제, 헤더 라우터 연결
  package-lock.json
  package.json
  src/apis/business.ts
  src/apis/member.ts
  src/apis/workplace.ts
  src/components/ListStyle.tsx
  src/components/LogoAndNotification.tsx
  src/components/notiContainer.tsx
  src/layouts/HeaderNoTitle.tsx
  src/layouts/HeaderWithTitle.tsx
  src/pages/ManagementPlacePage/components/ManagementPlaceCard.tsx
  src/pages/ManagementPlacePage/hooks/useDeleteBusinessPlace.ts
Labels: ✨ Feat

#112 ♻️ Refactor : 지도 및 검색, 상세페이지 개선
  src/apis/chat.ts
  src/pages/ChatListPage/index.tsx
  src/pages/ChatPage/components/MessageContainer.tsx
  src/pages/ChatPage/index.tsx
  src/pages/DetailPage/components/DetailNavigation.tsx
  src/pages/DetailPage/components/RoomSelect.tsx
  src/pages/DetailPage/components/TabComponent.tsx
  src/pages/DetailPage/index.tsx
  src/pages/MainPage/hooks/useGetWorkplaceData.tsx
  src/pages/ReservationPage/index.tsx
  src/pages/SearchPage/components/SelectTime.tsx
  src/typings/types.ts
Labels: ♻️ Refactor

#115 [Docs] CICD 워크플로우 작성
  .github/workflows/deployment.yml
Labels: 📝 Docs

#116 📝 Docs : 워크플로우 args 수정
  .github/workflows/deployment.yml
Labels: 📝 Docs

#117 📝 Docs : action 수정
  .github/workflows/deployment.yml
Labels: 📝 Docs

#118 📝 Docs : 버전에 따른 오류 발생 부분 수정
  .github/workflows/deployment.yml
Labels: 📝 Docs

#121 ♻️ Refactor : 상세 페이지 및 여러 피드백 반영
  src/pages/DetailPage/components/TabComponent.tsx
  src/pages/DetailPage/components/WorkPlaceReview.tsx
  src/pages/ModifySpace/components/SpaceModify.tsx
  src/pages/RegisterSpace/components/RoomComponent.tsx
  src/pages/RegisterSpace/components/SpaceForm.tsx
  src/pages/UserLogin/components/OAuth.tsx
  src/pages/UserSignUp/components/UserSignUpForm.tsx
Labels: ♻️ Refactor

#122 ✨ Feat : 메인페이지 맞춤형 추천 기능 구현
  src/apis/workplace.ts
  src/pages/MainPage/components/KakaoMap.tsx
  src/pages/MainPage/components/MainList.tsx
  src/pages/MainPage/components/StudyRoomCard.tsx
  src/pages/MainPage/hooks/useGetWorkplaceData.tsx
  src/pages/MainPage/index.tsx
  src/typings/types.ts
Labels: ✨ Feat

#123 🔧 Fix, ♻️ Refactor : 메인 및 검색 페이지 개선
  src/apis/chat.ts
  src/apis/workplace.ts
  src/layouts/MainLayout.tsx
  src/pages/ChatListPage/components/ChatCard.tsx
  src/pages/ChatListPage/hooks/useGetChatList.ts
  src/pages/ChatPage/components/ReceiveMessage.tsx
  src/pages/ChatPage/components/SendMessage.tsx
  src/pages/ChatPage/index.tsx
  src/pages/DetailPage/components/DetailNavigation.tsx
  src/pages/DetailPage/components/RoomSelect.tsx
  src/pages/DetailPage/components/TabComponent.tsx
  src/pages/MainPage/components/KakaoMap.tsx
  src/pages/MainPage/hooks/useGetWorkplaceData.tsx
  src/pages/MainPage/index.tsx
  src/pages/ManagementReserverPage/components/ReserverCard.tsx
  src/pages/PaymentPage/PaymentLoadingPage.tsx
  src/pages/PaymentPage/PaymentSuccessPage.tsx
  src/pages/ReservationListPage/components/ReservationDetailCard.tsx
  src/pages/ReservationPage/components/ImageCarousel.tsx
  src/pages/ReservationPage/index.tsx
  src/pages/ReviewListPage/components/MyReviewCard.tsx
  src/pages/SearchPage/components/PlaceSearch.tsx
  src/pages/SearchPage/components/SelectTime.tsx
  src/pages/SearchResult/index.tsx
  src/pages/WriteReviewPage/components/ReservationInfo.tsx
  src/typings/types.ts
Labels: ♻️ Refactor, 🔧 Fix

#125 🚚 Rename : notiContainer.tsx 파일 대문자로 수정
  src/components/notiContainer.tsx
Labels: 🗑️ Chore

#126 🗑️ Chore : NotiContainer 파일 재생성
  src/components/NotiContainer.tsx
Labels: 🗑️ Chore

#127 ✨ Feat : 채팅 기능 구현 완료
  src/apis/index.ts
  src/pages/ChatListPage/components/ChatCard.tsx
  src/pages/ChatPage/components/ReceiveMessage.tsx
  src/pages/ChatPage/components/SendMessage.tsx
  src/pages/DetailPage/components/DetailNavigation.tsx
  src/pages/DetailPage/index.tsx
  src/pages/RegisterSpace/components/RoomComponent.tsx
Labels: ✨ Feat

#128 ✨ Feat : 사용자 알림 조회 api 연결
  src/apis/member.ts
  src/pages/UserNotiPage/components/UserNotiCard.tsx
  src/pages/UserNotiPage/components/UserNotiList.tsx
  src/pages/UserNotiPage/hooks/useGetUserAlarm.ts
  src/typings/types.ts
Labels: ✨ Feat

#130 🔧 Fix : 채팅 기능 개선
  src/constants/constants.ts
  src/pages/ChatPage/components/ReceiveMessage.tsx
  src/pages/ChatPage/components/SendMessage.tsx
  src/pages/DetailPage/components/DetailNavigation.tsx
  src/pages/PaymentPage/components/ReservationPrice.tsx
  src/pages/ReservationPage/index.tsx
  src/pages/SearchResult/index.tsx
Labels: 🔧 Fix

#131 ✨ Feat, ♻️ Refactor : 사업자 알림 페이지 api 연결 및 마크업 수정, 실시간 알림 수정
  src/apis/business.ts
  src/components/NotificationProvider.tsx
  src/pages/HostNotiPage/components/HostNotiCard.tsx
  src/pages/HostNotiPage/components/HostNotiList.tsx
  src/pages/HostNotiPage/components/HostReservationNotiCard.tsx
  src/pages/HostNotiPage/components/HostReviewNotiCard.tsx
  src/pages/HostNotiPage/hooks/useGetBusinessNotification.ts
  src/pages/ManagementReserverPage/components/ReserverList.tsx
  src/store/notificationStore.ts
  src/typings/types.ts
Labels: ✨ Feat

#132 🔧 Fix, 📝 Docs : 결제 취소 개선 및 yml 파일 수정
  .github/workflows/deployment.yml
  src/pages/PaymentPage/components/PaymentButton.tsx
Labels: 📝 Docs, 🔧 Fix

#133 📝 Docs : asset 및 경로 수정
  .github/workflows/deployment.yml
  src/pages/UserLogin/components/UserLoginForm.tsx
Labels: 📝 Docs

#134 📝 Docs : 경로 재수정
  .github/workflows/deployment.yml
Labels: 📝 Docs

#135 ✨ Feat, 💄 Design : 사업자의 사업장 조회 타입 수정,추가 및 사업장의 룸 개수 불러오는 방식 변경, 헤더 조정
  src/apis/workplace.ts
  src/layouts/HeaderNoTitle.tsx
  src/layouts/HeaderOnlyTitle.tsx
  src/layouts/HeaderWithTitle.tsx
  src/layouts/MainLayout.tsx
  src/pages/BusinessLogin/components/BusinessLoginForm.tsx
  src/pages/BusinessSignUp/components/BusinessSignUpForm.tsx
  src/pages/DetailPage/index.tsx
  src/pages/HostMypage/components/HostButtonContainer.tsx
  src/pages/HostNotiPage/components/HostNotiList.tsx
  src/pages/HostNotiPage/components/HostReservationNotiCard.tsx
  src/pages/HostNotiPage/index.tsx
  src/pages/ManagementPlacePage/components/ManagementPlaceCard.tsx
  src/pages/ManagementPlacePage/components/ManagementPlaceList.tsx
  src/pages/ManagementPlacePage/hooks/useGetBusinessWorkplaces.ts
  src/pages/SearchResult/components/RoomCard.tsx
  src/pages/SearchResult/index.tsx
  src/pages/UserLogin/components/UserLoginForm.tsx
  src/pages/UserMypage/components/LatestReservation.tsx
  src/pages/UserMypage/components/UserButtonContainer.tsx
  src/pages/UserNotiPage/components/UserNotiCard.tsx
  src/pages/UserNotiPage/components/UserNotiList.tsx
  src/pages/UserNotiPage/index.tsx
  src/pages/UserSignUp/components/UserSignUpForm.tsx
  src/typings/types.ts
Labels: ✨ Feat, 💄 Design

#137 🔧 Fix : 채팅 및 버그 개선
  src/pages/ChatListPage/components/ChatCard.tsx
  src/pages/ChatListPage/hooks/useGetChatList.ts
  src/pages/ChatListPage/index.tsx
  src/pages/ChatPage/components/MessageContainer.tsx
  src/pages/ChatPage/components/ReceiveMessage.tsx
  src/pages/ChatPage/components/SendMessage.tsx
  src/pages/ChatPage/index.tsx
  src/pages/ModifySpace/components/RoomModify.tsx
  src/pages/ModifySpace/index.tsx
  src/pages/SearchResult/components/ResultBar.tsx
  src/pages/SearchResult/hooks/useGetSearchStudyRoom.ts
  src/pages/WriteReviewPage/index.tsx
Labels: 🔧 Fix

#138 ✨ Feat, 💄 Design : 예약 ON_HOLD, PAYMENT_FAIL처리, paymentsucces page 수정, 헤더 hr 위치 조정
  src/apis/reservation.ts
  src/components/LogoAndNotification.tsx
  src/pages/HostNotiPage/components/HostNotiList.tsx
  src/pages/ManagementReserverPage/components/ReserverList.tsx
  src/pages/ManagementReserverPage/hooks/useGetReserver.ts
  src/pages/ModifySpace/index.tsx
  src/pages/PaymentPage/PaymentSuccessPage.tsx
  src/pages/RegisterSpace/index.tsx
  src/pages/ReservationListPage/components/ReservationDetailCard.tsx
  src/pages/ReservationListPage/hooks/useGetAllMyReservations.ts
  src/pages/UserMypage/hooks/useGetLatestReservation.ts
  src/pages/WriteReviewPage/index.tsx
  src/store/notificationStore.ts
  src/typings/types.ts
Labels: ✨ Feat, 💄 Design

#139 💄 Design : 주문 상품 글자 잘리는 문제 스타일 수정
  src/pages/PaymentPage/PaymentSuccessPage.tsx
Labels: 💄 Design

#140 ♻️ Refactor : 이메일 수정 불가능하게 처리
  src/pages/ChatListPage/index.tsx
  src/pages/HostInfoEditPage/components/HostEditContainer.tsx
  src/pages/HostInfoEditPage/components/HostEditForm.tsx
  src/pages/ManagementReserverPage/components/ReserverList.tsx
  src/pages/ReservationListPage/components/ReservationDetailCard.tsx
  src/pages/UserInfoEditPage/components/UserEditContainer.tsx
  src/pages/UserInfoEditPage/components/UserEditForm.tsx
Labels: ♻️ Refactor

#141 ♻️ Refactor : 알림 이미지 타입 이름 수정
  src/pages/HostNotiPage/components/HostReviewNotiCard.tsx
  src/typings/types.ts
Labels: ♻️ Refactor

#143 📝 Docs : README 작성
  README.md
Labels: 📝 Docs
