Repository prgrms-web-devcourse-final-project/WEB1_2_BUMBLEBEE_FE, pull requests merged in 2024-11, with the labels that each got.

#3 💄 Design : 메인 레이아웃 추가 #1
  src/App.tsx
  src/layouts/HeaderOnlyTitle.tsx
  src/layouts/MainLayout.tsx
Labels: 💄Design

#4 💄 Design : 하단 네비게이션바 추가 #1
  .eslintrc.cjs
  src/App.tsx
  src/layouts/.gitkeep
  src/layouts/BottomNavigation.tsx
  src/layouts/MainLayout.tsx
Labels: 💄Design

#5 ✨ Feat : 라우터 설정
  src/main.tsx
  src/routes/.gitkeep
  src/routes/Router.tsx
Labels: ✨Feat

#10 💄 Design : 사용자 마이페이지 메인 화면 디자인 #6
  src/layouts/HeaderNoTitle.tsx
  src/layouts/HeaderOnlyTitle.tsx
  src/layouts/HeaderWithTitle.tsx
  src/pages/UserMypage/components/CategoryButton.tsx
  src/pages/UserMypage/components/LatestReservation.tsx
  src/pages/UserMypage/index.tsx
  src/routes/Router.tsx
Labels: 💄Design

#11 💄 Design : 회원가입 페이지 디자인 구현 #8
  .eslintrc.cjs
  src/index.css
  src/pages/BusinessLogin/index.tsx
  src/pages/BusinessSignUp/components/BusinessSignUpForm.tsx
  src/pages/BusinessSignUp/index.tsx
  src/pages/StartPage/index.tsx
  src/pages/UserLogin/index.tsx
  src/pages/UserSignUp/components/UserSignUpForm.tsx
  src/pages/UserSignUp/index.tsx
  src/routes/Router.tsx
  tailwind.config.ts
Labels: 💄Design

#12 Design : 메인페이지 디자인 구현 #7
  index.html
  src/App.tsx
  src/layouts/BottomNavigation.tsx
  src/pages/.gitkeep
  src/pages/MainPage/components/KakaoMap.tsx
  src/pages/MainPage/components/MainList.tsx
  src/pages/MainPage/components/StudyRoomCard.tsx
  src/pages/MainPage/index.tsx
  src/routes/Router.tsx
  tailwind.config.ts
Labels: 💄Design

#16 ✨ Feat : 지도 중심값 및 현위치값 얻기 완료 #7
  src/pages/MainPage/components/KakaoMap.tsx
Labels: ✨Feat

#17 💄 Design : 리뷰 작성 페이지 마크업 구현 #15
  src/index.css
  src/pages/UserMypage/components/LatestReservation.tsx
  src/pages/WriteReviewPage/components/ReservationInfo.tsx
  src/pages/WriteReviewPage/components/WriteReview.tsx
  src/pages/WriteReviewPage/index.tsx
  src/routes/Router.tsx
Labels: 💄Design

#19 ✨ Feat : 회원가입 페이지 기능 구현
  src/index.css
  src/pages/BusinessSignUp/components/BusinessNumber.tsx
  src/pages/BusinessSignUp/components/BusinessSignUpForm.tsx
  src/pages/UserSignUp/components/PhoneNumberInput.tsx
  src/pages/UserSignUp/components/SelectAges.tsx
  src/pages/UserSignUp/components/UserSignUpForm.tsx
Labels: ✨Feat

#21 💄 Design, ✨ Feat : 로그인 페이지 디자인 및 기능 구현
  public/KakaoLogo.svg
  public/NaverLogo.svg
  src/pages/BusinessLogin/components/BusinessLoginForm.tsx
  src/pages/BusinessLogin/index.tsx
  src/pages/BusinessSignUp/components/BusinessSignUpForm.tsx
  src/pages/UserLogin/components/UserLoginForm.tsx
  src/pages/UserLogin/index.tsx
  src/pages/UserSignUp/components/UserSignUpForm.tsx
Labels: ✨Feat, 💄Design

#27 💄 Design, ✨ Feat : 리뷰 관리 페이지 마크업 구현, LocalDateTime 변환 함수 생성
  src/pages/ReservationListPage/components/ReservationDetailCard.tsx
  src/pages/ReviewListPage/components/MyReviewCard.tsx
  src/pages/ReviewListPage/components/MyReviewList.tsx
  src/pages/ReviewListPage/index.tsx
  src/routes/Router.tsx
  src/utils/formatTime.ts
Labels: ✨Feat, 💄Design

#29 💄 Design, ✨ Feat : 검색 페이지 마크업 및 기능 구현 #14
  index.html
  package-lock.json
  package.json
  src/pages/MainPage/components/KakaoMap.tsx
  src/pages/MainPage/components/MainList.tsx
  src/pages/MainPage/components/StudyRoomCard.tsx
  src/pages/SearchPage/components/PlaceList.tsx
  src/pages/SearchPage/components/PlaceSearch.tsx
  src/pages/SearchPage/components/SelectDate/SelectDate.css
  src/pages/SearchPage/components/SelectDate/SelectDate.tsx
  src/pages/SearchPage/components/SelectPeople.tsx
  src/pages/SearchPage/components/SelectTime.tsx
  src/pages/SearchPage/index.tsx
  src/routes/Router.tsx
  tsconfig.app.json
Labels: ✨Feat, 💄Design

#30 💄 Design : 사업장 관리 페이지 마크업 구현
  src/pages/ManagementPlacePage/components/ManagementPlaceCard.tsx
  src/pages/ManagementPlacePage/components/ManagementPlaceList.tsx
  src/pages/ManagementPlacePage/index.tsx
  src/routes/Router.tsx
Labels: 💄Design

#32 💄 Design : 예약자 확인 페이지 마크업 구현
  src/components/ListStyle.tsx
  src/pages/ManagementPlacePage/components/ManagementPlaceCard.tsx
  src/pages/ManagementReserverPage/components/ReserverCard.tsx
  src/pages/ManagementReserverPage/components/ReserverList.tsx
  src/pages/ManagementReserverPage/index.tsx
  src/pages/ReservationListPage/components/ReservationDetailCard.tsx
  src/pages/UserMypage/components/LatestReservation.tsx
  src/pages/WriteReviewPage/components/ReservationInfo.tsx
  src/routes/Router.tsx
  src/utils/formatTime.ts
Labels: 💄Design

#34 💄Design ✨Feat : 공간 등록 페이지 사업장명/소개/오픈마감/전화번호 디자인 및 기능 구현
  package-lock.json
  package.json
  src/assets/icons/KakaoLogo.svg
  src/assets/icons/NaverLogo.svg
  src/pages/BusinessLogin/components/BusinessLoginForm.tsx
  src/pages/BusinessSignUp/components/BusinessNumber.tsx
  src/pages/BusinessSignUp/components/BusinessSignUpForm.tsx
  src/pages/RegisterSpace/components/PhoneNumber.tsx
  src/pages/RegisterSpace/components/SelectClosedTime.tsx
  src/pages/RegisterSpace/components/SelectOpenTime.tsx
  src/pages/RegisterSpace/components/SpaceForm.tsx
  src/pages/RegisterSpace/index.tsx
  src/pages/StartPage/index.tsx
  src/pages/UserLogin/components/UserLoginForm.tsx
  src/pages/UserSignUp/components/PhoneNumberInput.tsx
  src/pages/UserSignUp/components/UserSignUpForm.tsx
  src/routes/Router.tsx
Labels: ✨Feat, 💄Design

#35 💄Design, ✨Feat : 공간 등록 및 룸 추가 페이지 디자인 및 기능 (룸 이미지 제외)
  package-lock.json
  package.json
  src/index.css
  src/pages/AddRoom/components/CountPeople.tsx
  src/pages/AddRoom/components/RoomForm.tsx
  src/pages/AddRoom/components/RoomImage.tsx
  src/pages/AddRoom/index.tsx
  src/pages/RegisterSpace/components/Address.tsx
  src/pages/RegisterSpace/components/SelectClosedTime.tsx
  src/pages/RegisterSpace/components/SelectOpenTime.tsx
  src/pages/RegisterSpace/components/SpaceForm.tsx
  src/pages/RegisterSpace/components/WorkSpaceImage.tsx
  src/routes/Router.tsx
Labels: ✨Feat, 💄Design

#36 💄Design, ✨Feat : 검색 결과 페이지 마크업 및 기능 구현
  src/pages/SearchPage/components/PlaceList.tsx
  src/pages/SearchPage/components/PlaceSearch.tsx
  src/pages/SearchPage/components/SelectDate/SelectDate.tsx
  src/pages/SearchPage/components/SelectPeople.tsx
  src/pages/SearchPage/components/SelectTime.tsx
  src/pages/SearchPage/index.tsx
  src/pages/SearchResult/components/ResultBar.tsx
  src/pages/SearchResult/components/RoomCard.tsx
  src/pages/SearchResult/index.tsx
  src/routes/Router.tsx
  src/store/.gitkeep
  src/store/searchStore.ts
  src/typings/.gitkeep
  tsconfig.app.json
Labels: ✨Feat, 💄Design

#41 💄Design : 예약페이지 마크업 구현
  src/pages/ReservationPage/components/ImageCarousel.tsx
  src/pages/ReservationPage/components/ReservationBar.tsx
  src/pages/ReservationPage/components/ReservationDate/ReservationDate.css
  src/pages/ReservationPage/components/ReservationDate/ReservationDate.tsx
  src/pages/ReservationPage/components/ReservationPeople.tsx
  src/pages/ReservationPage/components/ReservationTime.tsx
  src/pages/ReservationPage/components/RoomDetail.tsx
  src/pages/ReservationPage/index.tsx
  src/pages/SearchResult/index.tsx
  src/routes/Router.tsx
  src/store/searchStore.ts
Labels: ✨Feat, 💄Design

#43 💄 Design : 모달 컴포넌트 마크업 구현
  src/components/Modal.tsx
  src/pages/ReservationListPage/components/ReservationDetailCard.tsx
  src/pages/ReservationListPage/components/ReservationList.tsx
Labels: 💄Design

#47 💄 Design : 결제 완료 페이지 마크업 구현 #46
  src/pages/PaymentSuccessPage/index.tsx
  src/routes/Router.tsx
Labels: 💄Design

#49 ✨ Feat : 공간 등록 및 룸 추가 페이지 기능 구현 마무리
  package-lock.json
  package.json
  src/pages/AddRoom/components/CountPeople.tsx
  src/pages/AddRoom/components/RoomForm.tsx
  src/pages/AddRoom/components/RoomImage.tsx
  src/pages/AddRoom/index.tsx
  src/pages/RegisterSpace/components/Address.tsx
  src/pages/RegisterSpace/components/PhoneNumber.tsx
  src/pages/RegisterSpace/components/RoomComponent.tsx
  src/pages/RegisterSpace/components/SelectClosedTime.tsx
  src/pages/RegisterSpace/components/SelectOpenTime.tsx
  src/pages/RegisterSpace/components/SpaceForm.tsx
  src/pages/RegisterSpace/components/WorkSpaceImage.tsx
  src/pages/RegisterSpace/index.tsx
  src/routes/Router.tsx
  src/typings/.gitkeep
  src/typings/Types.ts
Labels: ✨Feat

#50 💄 Design : 사용자, 사업자 정보 조회 페이지 마크업 구현
  src/components/CommonInput.tsx
  src/components/LabelWithInput.tsx
  src/components/Modal.tsx
  src/pages/HostInfoPage/components/HostInfoBox.tsx
  src/pages/HostInfoPage/components/HostInfoContainer.tsx
  src/pages/HostInfoPage/index.tsx
  src/pages/ReservationListPage/components/ReservationDetailCard.tsx
  src/pages/UserInfoPage/components/DeleteAccountButton.tsx
  src/pages/UserInfoPage/components/UserInfoBox.tsx
  src/pages/UserInfoPage/components/UserInfoContainer.tsx
  src/pages/UserInfoPage/index.tsx
  src/routes/Router.tsx
Labels: 💄Design, ♻️Refactor

#55 💄 Design, ✨ Feat : 사용자 정보 수정 페이지 마크업 및 기능구현
  src/components/CommonInput.tsx
  src/pages/HostInfoEditPage/index.tsx
  src/pages/UserInfoEditPage/components/UserEditContainer.tsx
  src/pages/UserInfoEditPage/index.tsx
  src/pages/UserInfoPage/components/UserInfoContainer.tsx
  src/routes/Router.tsx
Labels: ✨Feat, 💄Design

#56 💄Design, ✨Feat : 상세 페이지 디자인 및 기능 구현
  src/pages/DetailPage/components/DetailComponent.tsx
  src/pages/DetailPage/components/DetailNavigation.tsx
  src/pages/DetailPage/components/ReviewComponent.tsx
  src/pages/DetailPage/components/RoomSelect.tsx
  src/pages/DetailPage/components/TabComponent.tsx
  src/pages/DetailPage/components/WorkPlaceReview.tsx
  src/pages/DetailPage/index.tsx
  src/pages/RegisterSpace/components/RoomComponent.tsx
  src/pages/RegisterSpace/components/SpaceForm.tsx
  src/routes/Router.tsx
Labels: ✨Feat, 💄Design

#60 ✨Feat : 사용자 회원가입 페이지 생년월일 추가
  src/pages/UserSignUp/components/BirthInput.tsx
  src/pages/UserSignUp/components/PhoneNumberInput.tsx
  src/pages/UserSignUp/components/SelectAges.tsx
  src/pages/UserSignUp/components/UserSignUpForm.tsx
Labels: ✨Feat

#61 ♻️ Refactor : 생년월일 검증 정규식 함수 리팩토링 및 사용된 정규식 함수, 에러메세지 개별 파일로 분리
  src/constants/.gitkeep
  src/constants/constants.ts
  src/pages/HostInfoEditPage/components/HostEditForm.tsx
  src/pages/UserInfoEditPage/components/UserEditForm.tsx
  src/typings/Types.ts
  src/utils/.gitkeep
  src/utils/autoHyphen.ts
  src/utils/validationCheckRegex.ts
Labels: ♻️Refactor

#63 🏷️ Types : 기본 타입 정의 추가
  src/pages/AddRoom/components/CountPeople.tsx
  src/pages/AddRoom/components/RoomForm.tsx
  src/pages/RegisterSpace/components/PhoneNumber.tsx
  src/pages/RegisterSpace/components/RoomComponent.tsx
  src/pages/RegisterSpace/components/SelectClosedTime.tsx
  src/pages/RegisterSpace/components/SelectOpenTime.tsx
  src/pages/RegisterSpace/components/SpaceForm.tsx
  src/pages/RegisterSpace/components/WorkSpaceImage.tsx
  src/pages/RegisterSpace/index.tsx
  src/typings/Types.ts
  src/typings/types.ts
Labels: 🏷️Type

#64 ♻️ Refactor : 회원가입과 로그인 인풋 하이픈과 에러 적용하기
  src/constants/constants.ts
  src/pages/BusinessLogin/components/BusinessLoginForm.tsx
  src/pages/BusinessSignUp/components/BusinessNumber.tsx
  src/pages/BusinessSignUp/components/BusinessSignUpForm.tsx
  src/pages/RegisterSpace/components/PhoneNumber.tsx
  src/pages/UserLogin/components/UserLoginForm.tsx
  src/pages/UserSignUp/components/BirthInput.tsx
  src/pages/UserSignUp/components/PhoneNumberInput.tsx
  src/pages/UserSignUp/components/UserSignUpForm.tsx
  src/utils/autoHyphen.ts
  src/utils/validationCheckRegex.ts
Labels: ♻️ Refactor

#65 ✨Feat : axios 모듈화
  .env.default
  .eslintrc.cjs
  src/apis/.gitkeep
  src/apis/auth.ts
  src/apis/index.ts
  src/utils/auth.ts
Labels: ✨ Feat

#67 ✨Feat : 사업장 및 스터디룸, 예약 일부 api 구현
  src/apis/reservation.ts
  src/apis/workplace.ts
Labels: ✨ Feat

#70 ✨ Feat : 회원가입/로그인/프리사인드 api 구현
  src/apis/auth.ts
  src/apis/index.ts
  src/apis/workplace.ts
  src/utils/auth.ts
Labels: ✨ Feat

#71 🏷️ Types : 공통 타입 파일 수정
  src/apis/business.ts
  src/apis/member.ts
  src/apis/reservation.ts
  src/apis/review.ts
  src/apis/workplace.ts
  src/typings/types.ts
Labels: ♻️ Refactor

#72 ✨ Feat : 사업자, 사용자 마이페이지 api 연결 완료
  src/apis/reservation.ts
  src/pages/HostMypage/components/HostButtonContainer.tsx
  src/pages/HostMypage/components/HostCategoryButton.tsx
  src/pages/HostMypage/components/HostInfo.tsx
  src/pages/HostMypage/hooks/useGetBusinessData.ts
  src/pages/UserMypage/components/CategoryButton.tsx
  src/pages/UserMypage/components/LatestReservation.tsx
  src/pages/UserMypage/components/UserButtonContainer.tsx
  src/pages/UserMypage/components/UserInfo.tsx
  src/pages/UserMypage/hooks/useGetMyReservations.ts
  src/pages/UserMypage/hooks/useGetUserData.ts
  src/utils/formatTime.ts
Labels: ✨ Feat

#73 ✨ Feat : 토스페이먼츠 결제 연동
  .env.default
  package-lock.json
  package.json
  src/assets/icons/TossLogo.svg
  src/constants/constants.ts
  src/pages/PaymentPage/PaymentFailPage.tsx
  src/pages/PaymentPage/PaymentLoadingPage.tsx
  src/pages/PaymentPage/PaymentSuccessPage.tsx
  src/pages/PaymentPage/components/CancelRule.tsx
  src/pages/PaymentPage/components/PaymentAgree.tsx
  src/pages/PaymentPage/components/PaymentButton.tsx
  src/pages/PaymentPage/components/PaymentMethod.tsx
  src/pages/PaymentPage/components/PaymentRoomCard.tsx
  src/pages/PaymentPage/components/ReservationGuide.tsx
  src/pages/PaymentPage/components/ReservationInfo.tsx
  src/pages/PaymentPage/index.tsx
  src/pages/ReservationPage/components/ReservationBar.tsx
  src/pages/ReservationPage/components/ReservationTime.tsx
  src/pages/ReservationPage/index.tsx
  src/pages/SearchPage/components/SelectTime.tsx
  src/routes/Router.tsx
  src/store/searchStore.ts
  src/utils/formatTime.ts
  src/utils/validationCheckRegex.ts
  vite.config.ts
Labels: ✨ Feat

#74 ✨ Feat : 회원가입/로그인/소셜 로그인 api 연결
  .env.default
  src/apis/auth.ts
  src/apis/index.ts
  src/components/LogoutButton.tsx
  src/pages/BusinessLogin/components/BusinessLoginForm.tsx
  src/pages/BusinessLogin/hooks/useBusinessLogin.ts
  src/pages/BusinessSignUp/components/BusinessSignUpForm.tsx
  src/pages/BusinessSignUp/hooks/useBusinessSignUp.ts
  src/pages/UserLogin/components/OAuth.tsx
  src/pages/UserLogin/components/UserLoginForm.tsx
  src/pages/UserLogin/hooks/useUserLogIn.ts
  src/pages/UserSignUp/components/UserSignUpForm.tsx
  src/pages/UserSignUp/hooks/useUserSignUp.ts
  src/routes/Router.tsx
  src/store/authStore.ts
Labels: ✨ Feat

#77 ✨ Feat : api 수정
  src/apis/auth.ts
  src/apis/index.ts
Labels: ✨ Feat
