Repository prgrms-web-devcourse-final-project/WEB1_2_BUMBLEBEE_FE, pull requests merged in 2025-01, with the labels that each got.

#147 ♻️ Refactor : 코드 개선
  .eslintrc.cjs
  package-lock.json
  package.json
  src/components/CountPeople.tsx
  src/components/RoomForm.tsx
  src/components/RoomImage.tsx
  src/pages/ChatPage/components/MessageContainer.tsx
  src/pages/ChatPage/components/SendMessage.tsx
  src/pages/ChatPage/index.tsx
  src/pages/ModifySpace/components/RoomModify.tsx
  src/pages/PaymentPage/components/ReservationPrice.tsx
  src/pages/RegisterSpace/index.tsx
  src/pages/ReservationPage/components/ReservationTime.tsx
  src/pages/SearchPage/components/SelectTime.tsx
  src/routes/Router.tsx
Labels: ♻️ Refactor

#150 ♻️ Refactor : 예약 기능 개선
  src/pages/BusinessSignUp/hooks/useBusinessSignUp.ts
  src/pages/DetailPage/components/DetailComponent.tsx
  src/pages/DetailPage/components/RoomSelect.tsx
  src/pages/DetailPage/components/TabComponent.tsx
  src/pages/DetailPage/components/WorkPlaceReview.tsx
  src/pages/ReservationPage/components/ReservationDate/ReservationDate.tsx
  src/pages/ReservationPage/components/ReservationTime.tsx
  src/pages/SearchPage/components/SelectDate/SelectDate.tsx
  src/utils/formatTime.ts
Labels: ♻️ Refactor

#152 ✨ Feat : 리뷰 수정 및 삭제 기능 추가
  src/apis/review.ts
  src/pages/EditReviewPage/components/EditReview.tsx
  src/pages/EditReviewPage/hooks/useEditReview.ts
  src/pages/EditReviewPage/index.tsx
  src/pages/ReviewListPage/components/MyReviewCard.tsx
  src/pages/ReviewListPage/hooks/useDeleteReview.ts
  src/pages/UserInfoPage/components/UserInfoBox.tsx
  src/routes/Router.tsx
Labels: ✨ Feat

#155 ✨ Feat, 🔧 Fix, ♻️ Refactor : 결제 페이지 및 검색 결과 개선
  src/pages/PaymentPage/components/CollectionModal.tsx
  src/pages/PaymentPage/components/OfferModal.tsx
  src/pages/PaymentPage/components/PaymentAgree.tsx
  src/pages/PaymentPage/components/PaymentRoomCard.tsx
  src/pages/PaymentPage/components/ReservationGuide.tsx
  src/pages/PaymentPage/index.tsx
  src/pages/ReservationPage/index.tsx
  src/pages/SearchPage/components/PlaceSearch.tsx
  src/pages/SearchPage/components/SelectDate/SelectDate.tsx
  src/pages/SearchPage/components/SelectPeople.tsx
  src/pages/SearchPage/components/SelectTime.tsx
  src/store/searchStore.ts
Labels: ✨ Feat, ♻️ Refactor, 🔧 Fix

#156 ♻️ Refactor : 최근 7일 이내 알림 구분선 추가
  src/components/LogoAndNotification.tsx
  src/pages/HostNotiPage/components/HostNotiList.tsx
  src/pages/HostNotiPage/components/HostReviewNotiCard.tsx
  src/pages/UserNotiPage/components/UserNotiList.tsx
  src/store/notificationStore.ts
  src/utils/formatTime.ts
Labels: ♻️ Refactor

#157 Docs 📝 : README 맞춤형 추천 화면 추가
  README.md
Labels: 📝 Docs

#158 ♻️ Refactor : 예약 내역 페이지 로딩 시간 최적화 및 reissue 요청 401 응답 로그아웃 처리
  src/apis/index.ts
  src/pages/ReservationListPage/components/ReservationList.tsx
  src/pages/ReservationListPage/hooks/useGetAllMyReservations.ts
Labels: ♻️ Refactor

#160 ♻️ Refactor : 렌더링 시 isLoading 우선순위 변경
  src/pages/HostNotiPage/components/HostNotiList.tsx
  src/pages/HostNotiPage/hooks/useGetBusinessNotification.ts
  src/pages/ManagementReserverPage/components/ReserverList.tsx
  src/pages/ManagementReserverPage/hooks/useGetReserver.ts
  src/pages/ReviewListPage/components/MyReviewList.tsx
  src/pages/UserNotiPage/components/UserNotiList.tsx
Labels: ♻️ Refactor

#162 🔧 Fix, ♻️ Refactor : 룸 수정 페이지 개선 및 무한 리다이렉팅 버그 개선
  src/apis/index.ts
  src/components/RoomImage.tsx
  src/pages/ModifySpace/components/RoomModify.tsx
  src/pages/ModifySpace/components/SpaceModify.tsx
  src/pages/ModifySpace/index.tsx
  src/pages/RegisterSpace/components/RoomForm.tsx
  src/pages/RegisterSpace/components/SpaceForm.tsx
  src/pages/RegisterSpace/index.tsx
Labels: ♻️ Refactor, 🔧 Fix

#165 ♻️ Refactor : S3 이미지, 토큰, 채팅 개선
  src/apis/chat.ts
  src/apis/workplace.ts
  src/pages/ChatPage/index.tsx
  src/pages/MainPage/index.tsx
  src/pages/ModifySpace/components/RoomModify.tsx
  src/pages/PaymentPage/components/PaymentButton.tsx
  src/utils/auth.ts
Labels: ♻️ Refactor

#166 ♻️ Refactor : 채팅 읽음 처리 개선
  src/pages/ChatPage/index.tsx
Labels: ♻️ Refactor

#168 ♻️ Refactor : 맞춤형 추천 서버 안될 시 재요청 막도록 개선
  src/pages/MainPage/hooks/useGetWorkplaceData.tsx
Labels: ♻️ Refactor

#169 🔧 Fix : 예약 시간 선택, 검색 요청 버그 개선
  src/apis/index.ts
  src/pages/SearchPage/components/SelectDate/SelectDate.tsx
Labels: 🔧 Fix

#170 🗑️ Chore : 서버 확인을 위한 log 추가
  src/pages/ChatPage/index.tsx
Labels: 🗑️ Chore
